// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatrocinioZoneProyecto.Data;

#nullable disable

namespace PatrocinioZoneProyecto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119162720_AddMontoToPatrocinador")]
    partial class AddMontoToPatrocinador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatrocinioZoneProyecto.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clubes", (string)null);
                });

            modelBuilder.Entity("PatrocinioZoneProyecto.Models.Patrocinador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patrocinadores", (string)null);
                });

            modelBuilder.Entity("PatrocinioZoneProyecto.Models.ZonaPatrocinio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoReservado")
                        .HasColumnType("bit");

                    b.Property<int?>("PatrocinadorId")
                        .HasColumnType("int");

                    b.Property<int?>("PatrocinadorId1")
                        .HasColumnType("int");

                    b.Property<int>("Tamanio")
                        .HasColumnType("int");

                    b.Property<int>("Ubicacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PatrocinadorId");

                    b.HasIndex("PatrocinadorId1");

                    b.ToTable("ZonasPatrocinio", (string)null);
                });

            modelBuilder.Entity("PatrocinioZoneProyecto.Models.ZonaPatrocinio", b =>
                {
                    b.HasOne("PatrocinioZoneProyecto.Models.Club", "Club")
                        .WithMany("ZonasDePatrocinio")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatrocinioZoneProyecto.Models.Patrocinador", "Patrocinador")
                        .WithMany()
                        .HasForeignKey("PatrocinadorId");

                    b.HasOne("PatrocinioZoneProyecto.Models.Patrocinador", null)
                        .WithMany("Zonas")
                        .HasForeignKey("PatrocinadorId1");

                    b.Navigation("Club");

                    b.Navigation("Patrocinador");
                });

            modelBuilder.Entity("PatrocinioZoneProyecto.Models.Club", b =>
                {
                    b.Navigation("ZonasDePatrocinio");
                });

            modelBuilder.Entity("PatrocinioZoneProyecto.Models.Patrocinador", b =>
                {
                    b.Navigation("Zonas");
                });
#pragma warning restore 612, 618
        }
    }
}
